In [1]:
#1
import numpy as np
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
#2
a=np.zeros(5,dtype=int)
print(a)

[0 0 0 0 0]


In [12]:
#3
a=np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
#4
a=np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [14]:
#5
a=np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


In [15]:
#6
a=np.array([1,2,3])*3
print(a)

[3 6 9]


In [18]:
#7
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [24]:
#8
a=np.array([4,9,16,25])
print(np.sqrt(a))

[2. 3. 4. 5.]


In [21]:
#9
a=np.array([10,20,30,40])
print(np.mean(a))

25.0


In [30]:
#10
a=np.random.randint(1,5,5)
print(a)
print(np.sum(a))

[4 3 3 4 2]
16


In [35]:
#11
a=np.arange(1,11)
print(a)
print(a[0:5])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]


In [4]:
#12
import numpy as np
a=np.array([10,20,30,40,50])
print(a[-2::])

[40 50]


In [9]:
#13
a=np.array([1,2,3,4,5])
a[2]=99
print(a)

[ 1  2 99  4  5]


In [6]:
#14
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [28]:
#15
a=np.arange(1,11)
print(a)
print(a[-1:-11:-1])
print(a[::-1])


[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]


In [39]:
#16
a=np.random.randint(1,100)
print(a)
b=np.random.randint(1,100,(2,3,3))
print(b)

43
[[[44 36 48]
  [86 75 12]
  [56 44 37]]

 [[12 36 70]
  [70 41  5]
  [22 42 29]]]


In [40]:
#17
a=np.random.randint(1,50,(3,3))
print(a)

[[33 33 22]
 [43  1 41]
 [ 3 38 18]]


In [8]:
# Generate 5 random numbers from a normal distribution(doubt)
#18
import numpy as np
random_numbers = np.random.randn(5)
print(random_numbers)

[-0.13961038  0.51952471  0.26855941 -0.08589841  1.08406679]


In [42]:
#19
a=np.random.random(5)
print(a)


[0.66525213 0.85687462 0.304471   0.63681542 0.10938546]


In [48]:
#20
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[2 4 1 3 5]


In [56]:
#21
a=np.array([[1,2,3],[4,5,6]])
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


In [7]:
#22
a=np.arange(1,13)
print(a)
print(a.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [66]:
#23
a=np.arange(5)
print(a)
resize=np.resize(a,(3,3))
print(resize)

[0 1 2 3 4]
[[0 1 2]
 [3 4 0]
 [1 2 3]]


In [71]:
#24
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("2nd row:", a[1])
print("3rd column:", a[:, 2])



2nd row: [4 5 6]
3rd column: [3 6 9]


In [1]:
#1
import numpy as np
a=np.arange(1,11)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
#2
a=np.zeros(5,dtype=int)
print(a)

[0 0 0 0 0]


In [6]:
#3
a=np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
#4
a=np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [9]:
#5
a=np.arange(10,51,5)
print(a)


[10 15 20 25 30 35 40 45 50]


In [10]:
#6
a=np.array([1,2,3])*3
print(a)

[3 6 9]


In [12]:
#7
a=np.array([[1,2,3],[4,5,6]])
print(sum(a))

[5 7 9]


In [14]:
#8
a=np.array([10,20,30,40])
print(np.mean(a))

25.0


In [16]:
#9
a=np.array([4,9,16,25])
print(np.sqrt(a))


[2. 3. 4. 5.]


In [18]:
#10
a=np.random.randint(1,100,(5))
print(a)
print(sum(a))


[74 41 69 48 16]
248


In [19]:
#11
a=np.arange(1,11)
print(a[0:5])

[1 2 3 4 5]


In [24]:
#12
a=np.array([10,20,30,40,50])
print(a[-1:-3:-1])

[50 40]


In [26]:
#13
a=np.array([1,2,3,4,5])
a[2]=99
print(a)


[ 1  2 99  4  5]


In [36]:
#14
a=np.random.randint(1,10,size=(3,3))
print(a)
print(a[1,2])

[[8 2 6]
 [3 9 5]
 [5 3 7]]
5


In [38]:
#15
a=np.arange(1,11)
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [39]:
#16
a=np.random.randint(1,100)
print(a)

68


In [40]:
#17
a=np.random.randint(1,100,(3,3))
print(a)


[[ 4 83 91]
 [25 85 23]
 [37 39 25]]


In [41]:
#18
a=np.random.randn(5)
print(a)

[-0.06929313 -0.78303674  1.45963621  0.09287877 -0.61884675]


In [42]:
#19
a=np.random.random(10)
print(a)

[0.24878336 0.87747383 0.50346154 0.50130331 0.07820035 0.49454064
 0.17567435 0.84107351 0.0461536  0.25729985]


In [48]:
#20
a=np.array([1,2,3,4,5])
np.random.shuffle(a)
print(a)

[5 1 2 4 3]


In [50]:
#21
a=np.array([[1,2,3],[4,5,6]])
print(np.transpose(a))

[[1 4]
 [2 5]
 [3 6]]


In [54]:
#22
a=np.arange(1,13)
print(a)
print(a.reshape(3,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
#23
a=np.arange(1,6)
print(a)
print(np.resize(a,(3,3)))


[1 2 3 4 5]
[[1 2 3]
 [4 5 1]
 [2 3 4]]
