In [2]:
#version
import numpy as np
print(np.__version__)

2.1.3


In [3]:
#find type
a=[1,2,3,4,5]
print(a)
print(type(a))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
#find type of array
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
import numpy as np
arr=np.array([[[[1,2,3],[4,5,6]],[[3,2,1],[5,4,3]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
print(arr)

[[[[1 2 3]
   [4 5 6]]

  [[3 2 1]
   [5 4 3]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]


In [8]:
import numpy as np
a=np.array([[[[1,2,3],[4,5,6]],[[3,2,1],[5,4,3]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]])
b=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
c=np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(a.shape)
print(b.shape)
print(c.shape)
print(c*2)
print(a.size)
print(b.size)
print(c.size)




4
3
2
(1, 4, 2, 3)
(2, 2, 3)
(2, 3)
[[ 2  4  6]
 [ 8 10 12]]
24
12
6


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5],ndmin=5)
print(arr)
print("number of dimension:",arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension: 5


In [10]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[0]+a[1])

[ 7  9 11 13 15]


In [11]:
print(a[1,-1])

10


In [12]:
print(a[0,0]+a[1,1])

8


In [13]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.dtype)

int64


In [14]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.astype("float64"))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [15]:
#o=zeros matrix
import numpy as np
zeroarraay=np.zeros((3,3))
zeroarray=np.zeros((3,3),dtype=int)
print(zeroarraay)
print(zeroarray)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [16]:
#ones matrix
import numpy as np
onesarraay=np.ones((3,3))
onesarray=np.ones((3,3),dtype=int)
print(onesarraay)
print(onesarray)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
#for range(arange())
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [18]:
a=np.arange(0,9,2)
print(a)

[0 2 4 6 8]


In [30]:
#to select random integer
a=np.random.randint(1,10,size=(2,3,4,3))
print(a)

[[[[4 7 5]
   [9 4 2]
   [7 7 6]
   [2 8 7]]

  [[7 2 2]
   [3 4 1]
   [4 3 2]
   [5 4 3]]

  [[6 8 1]
   [8 7 3]
   [8 7 7]
   [1 3 9]]]


 [[[9 9 4]
   [5 8 1]
   [5 7 2]
   [6 4 3]]

  [[1 5 2]
   [7 6 7]
   [2 7 8]
   [7 5 8]]

  [[6 2 1]
   [6 3 9]
   [2 2 9]
   [1 9 9]]]]


In [31]:
#randomly select the positive and negative integers
a=np.random.randn(1,2,3,4)
print(a)

[[[[-1.8961762  -0.46438493 -0.51084515 -1.22436948]
   [-1.04523442  0.93643622 -2.0226935   0.121034  ]
   [ 0.68081481 -0.72416157  1.19811297  0.32500608]]

  [[-0.53998659  1.12233147 -0.92694275 -1.50994641]
   [-1.89252489  0.63807266 -0.0143885   0.387127  ]
   [-0.42336542 -0.31713034 -2.43609924 -1.54272142]]]]


In [32]:
#randomly select the numbers between 0 to one
a=np.random.random((1,2,3,4))
print(a)

[[[[0.47475853 0.38903969 0.86834724 0.60915898]
   [0.21783827 0.24153024 0.82135778 0.42672308]
   [0.31281823 0.14738547 0.18333872 0.33252597]]

  [[0.05166016 0.21307081 0.90970492 0.18554048]
   [0.18106476 0.11972281 0.81766468 0.80215589]
   [0.03944812 0.62108399 0.2442914  0.90437715]]]]


In [33]:
#full uses to mAake the matrix fully the specific number
a=np.full((3,3),25)
print(a)

[[25 25 25]
 [25 25 25]
 [25 25 25]]


In [34]:
#identity used to print the tht matrix diagonally 1
a=np.identity((3),dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [36]:
a=np.random.randint(20,30,size=(1,8,2))
print(a)

[[[25 25]
  [20 25]
  [25 25]
  [20 22]
  [20 22]
  [29 22]
  [22 28]
  [24 20]]]


In [38]:
import numpy as np
a=np.random.randint(1,10,size=(3,8))
print(a)

[[2 2 5 4 3 2 9 3]
 [3 1 9 7 9 4 4 6]
 [6 7 1 6 2 6 5 8]]


In [6]:
#in reshape the matrix should have equal elements
new_shape=(2,4,3)
rand=np.reshape(a,new_shape)
print(rand)

[[[8 7 1]
  [7 5 3]
  [2 5 9]
  [7 5 1]]

 [[9 7 9]
  [4 4 3]
  [5 3 1]
  [5 8 1]]]


In [7]:
a=np.random.randint(20,66,size=(2,3,4))
print(a)

[[[29 53 60 38]
  [24 60 50 53]
  [64 36 61 36]]

 [[25 23 39 36]
  [30 40 29 31]
  [50 21 43 63]]]


In [10]:
#in resize there is no need of matrix element have to be same
new_size=(4,5,2)
arr=np.resize(a,new_size)
print(arr)

[[[29 53]
  [60 38]
  [24 60]
  [50 53]
  [64 36]]

 [[61 36]
  [25 23]
  [39 36]
  [30 40]
  [29 31]]

 [[50 21]
  [43 63]
  [29 53]
  [60 38]
  [24 60]]

 [[50 53]
  [64 36]
  [61 36]
  [25 23]
  [39 36]]]


In [11]:
#used to make the marix as 1-D array
arr.flatten()

array([29, 53, 60, 38, 24, 60, 50, 53, 64, 36, 61, 36, 25, 23, 39, 36, 30,
       40, 29, 31, 50, 21, 43, 63, 29, 53, 60, 38, 24, 60, 50, 53, 64, 36,
       61, 36, 25, 23, 39, 36], dtype=int32)

In [14]:
#arithmetic operstion
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [22]:
#aggregate function
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

21
6
1
1.707825127659933
[5 7 9]
[ 6 15]


In [27]:
#slicing
slice=np.arange(10)
print(slice[2:5])


[2 3 4]


In [31]:
#slicing using step value
a=np.random.random(10)
print(a)
print(a[::2])

[0.37763068 0.8763537  0.70320903 0.65254992 0.0046208  0.17797324
 0.38501928 0.900646   0.82383048 0.32936716]
[0.37763068 0.70320903 0.0046208  0.38501928 0.82383048]


In [44]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0:2])
print(a[0,1])
print(a[1:2,-1:])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
2
[[6]]


In [65]:
a=np.array([[[3, 8, 6],
  [1, 7, 3],
  [2 ,4, 7]],

 [[4 ,7, 2],
  [2 ,9 ,7],
  [4 ,7, 6]],

 [[5 ,7, 2],
  [4, 8, 9],
  [1 ,5, 4]]])

print(a[1:2,:,1])



[[7 9 7]]
