In [1]:
import pandas as pd
number_series=pd.Series([2,4,6,8,10])
print(number_series)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [2]:
number_series=pd.Series([2,4,6,8,10],index=['a','b','c','d','e'],name="number")
print(number_series)
print(number_series['a'])
print(number_series[0])
                                        

a     2
b     4
c     6
d     8
e    10
Name: number, dtype: int64
2
2


C:\Users\Raghul\AppData\Local\Temp\ipykernel_38472\3945596326.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(number_series[0])


In [3]:
import numpy as np
dataframe=np.random.randint(1,3,(3,4))
print(dataframe)
another_dataframe=pd.DataFrame(dataframe,columns=['A','B','C','D'],index=["First","Second","Third"])
print(another_dataframe)


[[1 2 1 1]
 [1 1 2 1]
 [1 1 1 1]]
        A  B  C  D
First   1  2  1  1
Second  1  1  2  1
Third   1  1  1  1


In [40]:
value=[["Raghul",21],["Prajith",22],["Rahul",23]]
df=pd.DataFrame(value,columns=["Name","Age"])
print(df)

      Name  Age
0   Raghul   21
1  Prajith   22
2    Rahul   23


In [41]:
details={"Employee_Name":["Raghul","Prajith","Rahul","Roman"],"Income":[20000,30000,40000,45000]}
df=pd.DataFrame(details)
print(df)

  Employee_Name  Income
0        Raghul   20000
1       Prajith   30000
2         Rahul   40000
3         Roman   45000


In [42]:
values=[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6}]
df=pd.DataFrame(values)
print(df)

   a  b  c
0  1  2  3
1  4  5  6


In [43]:
a=[{"a":1,"c":3},{"a":4,"b":5,"c":6}]
df=pd.DataFrame(a)
print(df)

   a  c    b
0  1  3  NaN
1  4  6  5.0


In [45]:
actor_name=["vijay","ajith","suriya","dhanush"]
actor_age=[50,49,48,np.nan]
data=zip(actor_name,actor_age)
df=pd.DataFrame(data,columns=["Name","Age"])
print(df)


      Name   Age
0    vijay  50.0
1    ajith  49.0
2   suriya  48.0
3  dhanush   NaN


In [48]:
student_name=['raghul','prajith','rahul','jith','siva','siddiq','mani','simma']
tamil=[100,97,68,89,80,78,67,65]
english=[78,39,100,97,68,89,45,56]
science=[100,97,68,89,80,78,67,65]
maths=[77,45,67,89,100,97,68,89]
social=[100,97,68,89,67,45,90,67]
details=zip(student_name,tamil,english,science,maths,social)
df=pd.DataFrame(details,columns=['Name','Tamil','English','Science','Maths','social'],index=[1,2,3,4,5,6,7,8])
print(df)




      Name  Tamil  English  Science  Maths  social
1   raghul    100       78      100     77     100
2  prajith     97       39       97     45      97
3    rahul     68      100       68     67      68
4     jith     89       97       89     89      89
5     siva     80       68       80    100      67
6   siddiq     78       89       78     97      45
7     mani     67       45       67     68      90
8    simma     65       56       65     89      67


In [47]:
import pandas as pd
import numpy as np

# Student names
student_names = ["vijay", "ajith", "suriya", "dhanush", "Raghul", "Prajith", "Rahul", "Roman", "Ronie", "Cbum"]

# Subjects
subjects = ["Math", "Science", "English", "History", "Computer"]

# Create a DataFrame with random marks (between 50 and 100)
marks = pd.DataFrame(
    data=np.random.randint(50, 101, size=(len(student_names), len(subjects))),
    index=student_names,
    columns=subjects
)

# Display the DataFrame
print(marks)

         Math  Science  English  History  Computer
vijay      75       53       70       85        69
ajith      54       91       53       97        65
suriya     99       85       98       71        70
dhanush    76       89       71       96        67
Raghul     76       74       86       91        75
Prajith    81       58       86       84        95
Rahul      72       70       85       68        97
Roman      91       75       72       80        79
Ronie      55       78       51       75        70
Cbum       98       56       78       81        88


In [5]:
import pandas as pd
import numpy as np
a=np.random.randn(100,5)
df=pd.DataFrame(a,columns=["A","B","C","D","E"])
print(df)

           A         B         C         D         E
0   0.588570  0.171009 -1.115469  0.053284 -0.192562
1  -0.931136  2.088872  0.000324 -1.337716 -1.083088
2   0.659942 -2.431305 -0.831835 -0.733340  0.753076
3   0.410553 -0.921969  1.398447 -1.504562 -0.064992
4   0.593904 -0.181611 -1.237686 -0.316546 -3.186819
..       ...       ...       ...       ...       ...
95  1.486091 -0.199217  0.336043  0.404430 -0.947940
96 -1.139577 -1.475255  2.158662 -0.342877  0.907676
97  0.060352 -0.582413 -0.532449  0.978324 -0.597615
98 -1.332571 -0.082502  0.451455 -1.782218 -0.572735
99 -0.040374  1.412028 -0.055922 -0.805089  0.237123

[100 rows x 5 columns]


In [6]:
print(df.shape)

(100, 5)


In [10]:
print(df.head())
print(df.head(10))
print(df[40:51])

          A         B         C         D         E
0  0.588570  0.171009 -1.115469  0.053284 -0.192562
1 -0.931136  2.088872  0.000324 -1.337716 -1.083088
2  0.659942 -2.431305 -0.831835 -0.733340  0.753076
3  0.410553 -0.921969  1.398447 -1.504562 -0.064992
4  0.593904 -0.181611 -1.237686 -0.316546 -3.186819
          A         B         C         D         E
0  0.588570  0.171009 -1.115469  0.053284 -0.192562
1 -0.931136  2.088872  0.000324 -1.337716 -1.083088
2  0.659942 -2.431305 -0.831835 -0.733340  0.753076
3  0.410553 -0.921969  1.398447 -1.504562 -0.064992
4  0.593904 -0.181611 -1.237686 -0.316546 -3.186819
5 -1.081679  0.882220 -0.273300 -1.223538  1.967778
6  1.055410  0.450432  0.668683 -0.971580  0.535078
7  1.377741  0.302091 -0.883584  0.811074  1.023597
8 -0.695037 -0.835368  0.071003 -1.134940  1.107120
9  1.330059 -0.572180  0.210594 -0.658837 -0.370318
           A         B         C         D         E
40 -0.857922  1.926696 -1.712669 -2.003664  2.204847
41 -0.1329

In [20]:
print(df.tail())
print(df.tail(10))
print(df[-10:-1][::-1])

           A         B         C         D         E
95  1.486091 -0.199217  0.336043  0.404430 -0.947940
96 -1.139577 -1.475255  2.158662 -0.342877  0.907676
97  0.060352 -0.582413 -0.532449  0.978324 -0.597615
98 -1.332571 -0.082502  0.451455 -1.782218 -0.572735
99 -0.040374  1.412028 -0.055922 -0.805089  0.237123
           A         B         C         D         E
90  0.778571 -0.889111 -1.966222 -0.329487  1.920544
91  0.240460 -0.014864 -2.340852 -0.276214  1.398495
92 -1.189785 -1.531236 -0.052661 -0.696896 -1.361116
93 -0.975753 -1.638325  1.409302  0.367221 -1.630588
94 -0.762594 -0.132692 -1.598056  1.413973 -0.389224
95  1.486091 -0.199217  0.336043  0.404430 -0.947940
96 -1.139577 -1.475255  2.158662 -0.342877  0.907676
97  0.060352 -0.582413 -0.532449  0.978324 -0.597615
98 -1.332571 -0.082502  0.451455 -1.782218 -0.572735
99 -0.040374  1.412028 -0.055922 -0.805089  0.237123
           A         B         C         D         E
98 -1.332571 -0.082502  0.451455 -1.782218 -0.

In [18]:
print(list(df.columns))

['A', 'B', 'C', 'D', 'E']


In [21]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       100 non-null    float64
 1   B       100 non-null    float64
 2   C       100 non-null    float64
 3   D       100 non-null    float64
 4   E       100 non-null    float64
dtypes: float64(5)
memory usage: 4.0 KB
None
